name: CI + Release

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD
        uses: actions/checkout@v4

      - name: Use Node.js 21.7.3
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      - name: Use latest
        run: npm update

      - name: Restore dependencies
        run: npm ci

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.5.6.7