name: CI + Release

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
        
      - name: Generate build
        env:
          CI: false
        run: npm run build

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-build
          path: build

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "github-actions-build"
          tag: v1.1.0
