name: CI + Release

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD
        uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      # Share artifact inside workflow
      - name: Share artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-actions-build
          path: build

      - name: Install NPM
        run: npm install

      - name: Use latest
        run: npm update

      - name: Restore dependencies
        run: npm ci

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.5.6.6